// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAelm34pEhF4Qxo4xQpiu-fa7fNlZ9c_KM',
    appId: '1:842571916612:web:5641e083293d3e1dc7a311',
    messagingSenderId: '842571916612',
    projectId: 'money-flutter-project',
    authDomain: 'money-flutter-project.firebaseapp.com',
    storageBucket: 'money-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsUpVK1pO4X5jytIBaE_ZtobX8pRrz6Ro',
    appId: '1:842571916612:android:514f85ab843062b9c7a311',
    messagingSenderId: '842571916612',
    projectId: 'money-flutter-project',
    storageBucket: 'money-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROjIZITVLOfQGkcPaE2lH_bHjZNSI2kM',
    appId: '1:842571916612:ios:0c9b6cfa3bb8849ec7a311',
    messagingSenderId: '842571916612',
    projectId: 'money-flutter-project',
    storageBucket: 'money-flutter-project.appspot.com',
    iosClientId: '842571916612-b6tm7hhkpko24jnlgceloevs8bc3eh94.apps.googleusercontent.com',
    iosBundleId: 'com.example.money',
  );
}
